name: ci for Generic.Base.Api
on:
  push:
    paths:
      - Generic.Base.Api/**
  workflow_dispatch:
permissions:
  contents: read
  packages: write
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPORT_XML: doc/coverage/Generic.Base.Api-altcover.xml
      REPORT_TARGET: doc/coverage
      ASSEMBLY_FILTERS: -*.Tests;-AltCover.Monitor
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: add package source
      run: |
        dotnet new nugetconfig
        dotnet nuget add source https://nuget.pkg.github.com/MichaelDiers/index.json --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text 
        dotnet add ${{env.test-project}} package altcover
        dotnet build --configuration Release 
        dotnet test --configuration Release --no-build --filter "TestType=InMemoryIntegrationTest|TestType=UnitTest" /p:AltCover=true --no-build --no-restore /p:AltCoverReport="${{ env.altcover-xml }}" /p:AltCoverAssemblyFilter=xunit.*
      env:
        altcover-xml: ../../doc/coverage/Generic.Base.Api-altcover.xml
        test-project: Generic.Base.Api.Tests
      working-directory: Generic.Base.Api
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.x
        dotnet-quality: 'ga'
    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.1.26
      with:
        reports: ${{ env.REPORT_XML }}
        targetdir: ${{ env.REPORT_TARGET }}
        reporttypes: Html_Dark
        assemblyfilters: ${{ env.ASSEMBLY_FILTERS }}
        title: "WebApi.NetCore Code Coverage"
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: ${{ env.REPORT_TARGET }}
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
