name: ci for Generic.Base.Api
on:
  push:
    paths:
      - Generic.Base.Api/**
  workflow_dispatch:
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      altcover-xml: ../doc/coverage/altcover.xml
      working-directory: Generic.Base.Api
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: add package source
      run: |
        dotnet new nugetconfig
        dotnet nuget add source https://nuget.pkg.github.com/MichaelDiers/index.json --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text 
      working-directory: ${{env.working-directory}}
    - name: add packages
      run: dotnet add package altcover
      working-directory: ${{env.working-directory}}/${{env.working-directory}}.Tests
    - name: build
      run: dotnet build --configuration Release /p:Version=${VERSION}
      working-directory: ${{env.working-directory}}
    - name: test
      run: dotnet test --configuration Release /p:Version=${VERSION} --no-build --filter "TestType=InMemoryIntegrationTest|TestType=UnitTest" /p:AltCover=true --no-build --no-restore /p:AltCoverReport="${{ env.altcover-xml }}" /p:AltCoverAssemblyFilter=xunit.*
      working-directory: ${{env.working-directory}}
    