name: WebApi.NetCore
on:
  push:
    paths:
      - WebApi.NetCore/**
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release
      SOLUTION_PATH: WebApi.NetCore/WebApi.NetCore.sln
    steps:
      - uses: actions/checkout@v3
      - run: 'dotnet build ${{ env.SOLUTION_PATH }} -c ${{ env.CONFIGURATION }}'
      - run: 'dotnet test ${{ env.SOLUTION_PATH }} --filter "TestType=InMemoryIntegrationTest|TestType=UnitTest" -c ${{ env.CONFIGURATION }} --no-build --no-restore'
  doc:
    needs: test
    runs-on: ubuntu-latest
    env:
      CONFIGURATION: Release
      SOLUTION_PATH: WebApi.NetCore/WebApi.NetCore.sln
      TEST_PROJ_PATH: WebApi.NetCore/WebApi.NetCore.Api.Tests/WebApi.NetCore.Api.Tests.csproj
      ALTCOVER_XML: ../../doc/coverage/altcover.xml
      REPORT_XML: doc/coverage/altcover.xml
      REPORT_TARGET: doc/coverage
      ASSEMBLY_FILTERS: -*.Tests;-AltCover.Monitor
    steps:
      - uses: actions/checkout@v3
      - run: 'dotnet build ${{ env.SOLUTION_PATH }} -c ${{ env.CONFIGURATION }}'
      - run: 'dotnet test ${{ env.SOLUTION_PATH }} --filter "TestType=InMemoryIntegrationTest|TestType=UnitTest" /p:AltCover=true --no-build --no-restore /p:AltCoverReport="${{ env.ALTCOVER_XML }}" /p:AltCoverAssemblyFilter=xunit.*'
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.x
          dotnet-quality: 'ga'
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@5.1.26
        with:
          reports: ${{ env.REPORT_XML }}
          targetdir: ${{ env.REPORT_TARGET }}
          reporttypes: Html_Dark
          assemblyfilters: ${{ env.ASSEMBLY_FILTERS }}
          title: "WebApi.NetCore Code Coverage"
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ env.REPORT_TARGET }}
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
